// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHyLjZ4OCOsD7jKRAdUJ1CNPzBHqhD028',
    appId: '1:492670365608:web:2847ef3e424cb6cf09f79d',
    messagingSenderId: '492670365608',
    projectId: 'ai-algo-arena',
    authDomain: 'ai-algo-arena.firebaseapp.com',
    storageBucket: 'ai-algo-arena.firebasestorage.app',
    measurementId: 'G-XV0FFHSNTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZxMTPxMlPIEBoG052XKeJNBMpDWTzvlA',
    appId: '1:492670365608:android:32ca66e102dbc7a609f79d',
    messagingSenderId: '492670365608',
    projectId: 'ai-algo-arena',
    storageBucket: 'ai-algo-arena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp6StpKDp86txa0r8wHRauIOPBIhdhSKQ',
    appId: '1:492670365608:ios:13d0c23c22dc29c809f79d',
    messagingSenderId: '492670365608',
    projectId: 'ai-algo-arena',
    storageBucket: 'ai-algo-arena.firebasestorage.app',
    iosBundleId: 'com.example.aiAlgoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp6StpKDp86txa0r8wHRauIOPBIhdhSKQ',
    appId: '1:492670365608:ios:13d0c23c22dc29c809f79d',
    messagingSenderId: '492670365608',
    projectId: 'ai-algo-arena',
    storageBucket: 'ai-algo-arena.firebasestorage.app',
    iosBundleId: 'com.example.aiAlgoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHyLjZ4OCOsD7jKRAdUJ1CNPzBHqhD028',
    appId: '1:492670365608:web:9171627a15b6d2f809f79d',
    messagingSenderId: '492670365608',
    projectId: 'ai-algo-arena',
    authDomain: 'ai-algo-arena.firebaseapp.com',
    storageBucket: 'ai-algo-arena.firebasestorage.app',
    measurementId: 'G-FPJEN1E4W2',
  );
}
